const base = window.JINKE_BASE || '/';
const dataUrl = name => `${base}data/${name}`.replace(/\/+/g,'/').replace(':/','://');
const defaults={limit:50,basemap:'explore',fill:'#68c7c1',outline:'#16877f',opacity:.38,width:2,showPoly:true,showStations:true,showLabels:true,stationSize:7};
const state={...defaults,...JSON.parse(localStorage.getItem('jinkeAppearance')||'{}')};
const raster=(tiles,attribution)=>({version:8,sources:{r:{type:'raster',tiles,tileSize:256,attribution}},layers:[{id:'r',type:'raster',source:'r'}]});
const styles={
  transit:raster(['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],'© OpenStreetMap contributors. Apple-inspired controls only; no Apple Maps data.'),
  explore:raster(['https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png','https://b.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png'],'© OpenStreetMap contributors © CARTO. Apple Explore-inspired visual treatment only.'),
  dark:raster(['https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png'],'© OpenStreetMap contributors © CARTO'),
  satellite:raster(['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],'Tiles © Esri — review Esri terms, attribution, and domain restrictions before public production use.'),
  pastel:raster(['https://tiles.stadiamaps.com/tiles/stamen_watercolor/{z}/{x}/{y}.jpg'],'© Stadia Maps © Stamen Design © OpenStreetMap contributors — Stadia may require key/domain setup.'),
  mono:raster(['https://a.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}{r}.png'],'© OpenStreetMap contributors © CARTO')
};
document.querySelector('#app').innerHTML=`<main><section id="map" aria-label="Reach area map"></section><aside class="panel" aria-label="Map controls"><div id="sample" class="sample" hidden role="alert"></div><h1>金科路 Reach Map</h1><p id="stats">Loading…</p><div class="segments" role="group" aria-label="Total time limit">${[10,20,30,40,50].map(l=>`<button data-limit="${l}" aria-pressed="false">${l}</button>`).join('')}</div><label>Basemap<select id="basemap">${Object.keys(styles).map(k=>`<option>${k}</option>`).join('')}</select></label><p class="provider" id="provider"></p><label>Station search<input id="search" list="stations" placeholder="Search station"/><datalist id="stations"></datalist></label><label>Fill<input id="fill" type="color"/></label><label>Outline<input id="outline" type="color"/></label><label>Opacity<input id="opacity" type="range" min="0" max="1" step="0.01"/></label><label>Outline width<input id="width" type="range" min="0" max="8" step="0.5"/></label><label>Station size<input id="stationSize" type="range" min="3" max="18" step="1"/></label><label><input id="showPoly" type="checkbox"/> Show polygon</label><label><input id="showStations" type="checkbox"/> Show stations</label><label><input id="showLabels" type="checkbox"/> Show labels</label><div class="actions"><button id="fit">Fit to area</button><button id="full">Fullscreen</button><button id="reset">Reset appearance</button></div></aside></main>`;
const map=new maplibregl.Map({container:'map',style:styles[state.basemap],center:[121.597836,31.2064028],zoom:10}); map.addControl(new maplibregl.NavigationControl(),'bottom-right');
let stations, areas, manifest;
const save=()=>localStorage.setItem('jinkeAppearance',JSON.stringify(state));
const selected=()=>({type:'FeatureCollection',features:areas.features.filter(f=>f.properties.limit===state.limit)});
function stationData(){return {type:'FeatureCollection',features:stations.features.map(f=>{const a=f.properties.apple; return {...f,properties:{...f.properties,selected_limit:state.limit,remaining_walk_minutes:Math.max(0,state.limit-a),status:a<state.limit?'included':a===state.limit?'boundary':'excluded'}}})};}
function paint(){ if(!map.getSource('areas')) return; map.getSource('areas').setData(selected()); map.getSource('stations').setData(stationData()); map.setPaintProperty('reach-fill','fill-color',state.fill); map.setPaintProperty('reach-fill','fill-opacity',state.showPoly?state.opacity:0); map.setPaintProperty('reach-line','line-color',state.outline); map.setPaintProperty('reach-line','line-width',state.showPoly?state.width:0); map.setPaintProperty('station-circle','circle-radius',state.showStations?['case',['get','is_jinke'],state.stationSize+3,state.stationSize]:0); map.setLayoutProperty('station-label','visibility',state.showLabels?'visible':'none'); document.querySelectorAll('[data-limit]').forEach(b=>{const active=b.dataset.limit==String(state.limit); b.classList.toggle('active',active); b.setAttribute('aria-pressed',String(active));}); const f=selected().features[0]; document.getElementById('stats').textContent=`${state.limit} min: ${f.properties.included_stations} included, ${f.properties.boundary_stations} boundary stations`; document.getElementById('provider').textContent=styles[state.basemap].sources.r.attribution; save(); }
function wire(){ ['fill','outline','opacity','width','stationSize'].forEach(id=>{const el=document.getElementById(id); el.value=state[id]; el.oninput=()=>{state[id]=el.type==='range'?Number(el.value):el.value; paint();};}); ['showPoly','showStations','showLabels'].forEach(id=>{const el=document.getElementById(id); el.checked=state[id]; el.onchange=()=>{state[id]=el.checked; paint();};}); document.querySelectorAll('[data-limit]').forEach(b=>b.onclick=()=>{state.limit=Number(b.dataset.limit); paint();}); const bm=document.getElementById('basemap'); bm.value=state.basemap; bm.onchange=()=>{state.basemap=bm.value; save(); map.setStyle(styles[state.basemap]); map.once('styledata',addLayers);}; document.getElementById('fit').onclick=()=>{const coords=selected().features[0].geometry.coordinates.flat(3); const b=new maplibregl.LngLatBounds(); for(let i=0;i<coords.length;i+=2)b.extend([coords[i],coords[i+1]]); map.fitBounds(b,{padding:50});}; document.getElementById('full').onclick=()=>document.documentElement.requestFullscreen(); document.getElementById('reset').onclick=()=>{Object.assign(state,defaults); save(); location.reload();}; document.getElementById('search').onchange=e=>{const f=stations.features.find(x=>x.properties.station===e.target.value); if(f) map.flyTo({center:f.geometry.coordinates,zoom:13});}; }
function addLayers(){ if(map.getSource('areas')) return; map.addSource('areas',{type:'geojson',data:selected()}); map.addLayer({id:'reach-fill',type:'fill',source:'areas',paint:{'fill-color':state.fill,'fill-opacity':state.opacity}}); map.addLayer({id:'reach-line',type:'line',source:'areas',paint:{'line-color':state.outline,'line-width':state.width}}); map.addSource('stations',{type:'geojson',data:stationData()}); map.addLayer({id:'station-circle',type:'circle',source:'stations',paint:{'circle-color':['case',['get','is_jinke'],'#f59e0b',['==',['get','status'],'included'],'#136f63',['==',['get','status'],'boundary'],'#ffffff','#9ca3af'],'circle-stroke-color':['case',['==',['get','status'],'boundary'],'#111827','#fff'],'circle-stroke-width':2,'circle-radius':state.stationSize}}); map.addLayer({id:'station-label',type:'symbol',source:'stations',layout:{'text-field':['get','station'],'text-size':12,'text-offset':[0,1.2]},paint:{'text-halo-color':'#fff','text-halo-width':1}}); map.on('click','station-circle',e=>{const p=e.features[0].properties; new maplibregl.Popup().setLngLat(e.features[0].geometry.coordinates).setHTML(`<b>${p.station}</b><br/>Apple transit: ${p.apple} min<br/>Remaining walk: ${Math.max(0,state.limit-p.apple)} min<br/>Selected limit: ${state.limit} min`).addTo(map);}); paint(); }
Promise.all([fetch(dataUrl('reach-areas.geojson')).then(r=>r.json()),fetch(dataUrl('stations.geojson')).then(r=>r.json()),fetch(dataUrl('manifest.json')).then(r=>r.json())]).then(([a,s,m])=>{areas=a; stations=s; manifest=m; if(!manifest.production_data){const n=document.getElementById('sample'); n.hidden=false; n.textContent='Development sample data — production ORS polygons have not been generated yet. Do not use this map as final coverage.';} document.getElementById('stations').innerHTML=s.features.map(f=>`<option value="${f.properties.station}">`).join(''); wire(); map.on('load',addLayers);});
